name: devenv
reportingTeam: fnd-dtss
description: ""
oss: true
slack: ""
library: true
commands:
  - devenv
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  terraform: 0.14.7
arguments:
  dependencies:
    optional: []
    required: []
  description: ""
  reportingTeam: fnd-dtss
  type: []
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
