name: devenv
reportingTeam: cia-dev-tooling
library: true
releaseType: semver
versions:
  go: 1.17.1
  goreleaser: 0.157.0
  terraform: 0.14.7
releaseOptions:
  allowMajorVersions: true
  allowPrereleases: true
commands:
  - devenv
  # Doesn't use the bootstrap CLI setup
  #- snapshot-uploader
