name: devenv
reportingTeam: fnd-dtss
description: A kubernetes powered developer environment.
oss: true
slack: ""
library: true
commands:
  - devenv
circleAPIKey: ""
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  terraform: 0.14.7
arguments:
  circleAPIKey: ""
  dependencies:
    optional: []
    required: []
  description: A kubernetes powered developer environment.
  opslevel:
    confluenceSpaceKey: DTSS
    designDocumentLink: ""
  oss: true
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
