name: devenv
reportingTeam: fnd-dtss
description: Kubernetes Developer Environment Platform
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - devenv
circleAPIKey: ""
lintroller: bronze
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  terraform: 0.14.7
arguments:
  circleAPIKey: ""
  commands:
    - devenv
  dependencies:
    optional: []
    required: []
  description: Kubernetes Developer Environment Platform
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: bronze
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
  reportingTeam: fnd-dtss
  service: false
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
    version: v0.3.0-rc.2
  - name: github.com/getoutreach/stencil-golang
    version: v0.3.0-rc.4
  - name: github.com/getoutreach/stencil-opslevel
    version: v0.0.2-rc.5
  - name: github.com/getoutreach/stencil-circleci
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
