name: devenv
reportingTeam: fnd-dtss
description: Kubernetes Developer Environment Platform
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - devenv
circleAPIKey: ""
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  terraform: 0.14.7
arguments:
  circleAPIKey: ""
  commands:
    - devenv
  dependencies:
    optional: []
    required: []
  description: Kubernetes Developer Environment Platform
  grpcClients: []
  opslevel:
    confluenceSpaceKey: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    allowPrereleases: true
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - name: github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
