name: devenv
reportingTeam: fnd-dtss
description: Kubernetes Developer Environment Platform
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - devenv
circleAPIKey: ""
lintroller: bronze
tracing: honeycomb
metrics: datadog
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  terraform: 0.14.7
arguments:
  circleAPIKey: ""
  commands:
    - devenv
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: Kubernetes Developer Environment Platform
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: bronze
  metrics: datadog
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
  reportingTeam: fnd-dtss
  resources: {}
  service: false
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-opslevel
  - name: github.com/getoutreach/stencil-outreach
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
