name: devenv
reportingTeam: fnd-dtss
oss: true
library: true
releaseType: semver
versions:
  terraform: 0.14.7
releaseOptions:
  allowMajorVersions: true
  allowPrereleases: true
commands:
  - devenv
  # Doesn't use the bootstrap CLI setup
  #- snapshot-uploader
