apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minio
  namespace: kube-system
spec:
  chart: minio
  version: 3.5.2
  repo: https://charts.min.io/
  targetNamespace: minio
  valuesContent: |-
    # From: https://hub.docker.com/r/minio/minio/tags/?page=1&ordering=last_updated
    image:
      tag: RELEASE.2022-02-07T08-17-33Z
    # From: https://quay.io/repository/minio/mc?tag=latest&tab=tags
    mcImage:
      tag: RELEASE.2022-02-07T09-25-34Z
    buckets:
    - name: velero
      policy: none
      purge: false
    - name: velero-restore
      policy: none
      purge: false
    - name: outreach-polaroid-bento1a
      policy: none
      purge: false

    mode: standalone
    replicas: 1

    resources:
      requests:
        memory: 200Mi

    persistence:
      size: 5Gi

    # These credentials ARE INSECURE, but this is just for a local / restricted access
    # cloud devenv so this is currently acceptable. Potentially in the future we will
    # lock these down.
    users:
    - accessKey: console
      secretKey: console123
      policy: consoleAdmin
    - accessKey: minioaccess
      secretKey: miniosecret
      policy: readwrite
