apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  version: v1.7.1
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
