apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  version: v1.6.2 # intentionally set latest version that support v1alpha2 api
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
