apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart: metrics-server
  version: 3.8.2
  repo: https://kubernetes-sigs.github.io/metrics-server/
  targetNamespace: kube-system
  valuesContent: |-
    args: [--kubelet-insecure-tls]
