version: 2.1

orbs:
  shared: getoutreach/shared@1.38.1

jobs:
  ###Block(circleJobs)
  ###EndBlock(circleJobs)

  test:
    executor:
      name: shared/testbed-docker
      docker_tag: stable
    resource_class: large
    docker:
      - image: gcr.io/outreach-docker/bootstrap/ci:stable
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_ACCOUNT
    environment:
      ###Block(testEnvVars)
      ###EndBlock(testEnvVars)
    steps:
      - shared/setup_environment:
          setup_remote_docker: true
      - run:
          name: Wait for Infrastructure to be Ready
          command: ./scripts/shell-wrapper.sh ci/testing/wait-for-infra.sh
      - shared/with_go_cache
      - run:
          name: Run unit tests
          # Store the results of our tests in the $TEST_RESULTS directory
          command: make test | tee ${TEST_RESULTS}/go-test.out
      - run:
          name: Upload Code Coverage
          command: ./scripts/shell-wrapper.sh ci/testing/coveralls.sh
      - shared/save_go_cache # We save at the end because binaries are included with this
      - shared/upload_test_results

  ### Deviation(docker): We build a docker image in release
  release-dryrun:
    executor:
      name: shared/testbed-machine
    resource_class: xlarge
    steps:
      - shared/setup_environment:
          machine: true
      - shared/with_go_cache
      - shared/with_node_cache:
          save: true
      - run:
          name: Setting up Docker Builder
          command: |-
            # Setup buildkit for arm64
            source "./.bootstrap/shell/lib/buildx.sh"
      - run:
          name: Release (Dry-run)
          command: ./scripts/shell-wrapper.sh ci/release/dryrun.sh
      - shared/save_go_cache # We save at the end because binaries are included with this
  release:
    executor:
      name: shared/testbed-machine
    resource_class: xlarge
    steps:
      - shared/setup_environment:
          machine: true
      - shared/with_go_cache
      - shared/with_node_cache:
          save: true
      - run:
          name: Setting up Docker Builder
          command: |-
            # Setup buildkit for arm64
            source "./.bootstrap/shell/lib/buildx.sh"
      - run:
          name: Release
          command: GH_TOKEN=$OUTREACH_GITHUB_TOKEN yarn --frozen-lockfile semantic-release
      - shared/save_go_cache # We save at the end because binaries are included with this

  trigger_documentation:
    executor:
      name: shared/testbed-docker
      docker_tag: stable
    steps:
      - shared/setup_environment
      - shared/with_go_cache
      - run:
          name: Trigger Documentation Update
          command: ./scripts/shell-wrapper.sh ci/release/docs.sh

workflows:
  version: 2
  ###Block(circleWorkflows)
  ###EndBlock(circleWorkflows)
  build_and_test:
    jobs:
      ###Block(circleWorkflowJobs)
      ###EndBlock(circleWorkflowJobs)
      - release:
          context:
            - docker-registry
            - ghaccesstoken
            - npm-credentials
          requires:
            - test
          ###Block(circleReleaseRequires)
          ###EndBlock(circleReleaseRequires)
          filters:
            branches:
              only:
                - master
                - main
                - rc
      - release-dryrun:
          context:
            - docker-registry
            - ghaccesstoken
            - npm-credentials
          filters:
            branches:
              ignore:
                - master
                - main
                - rc
      - test:
          context:
            - docker-registry
            - ghaccesstoken
            - npm-credentials
      - trigger_documentation:
          context:
            - docker-registry
            - ghaccesstoken
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
