apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: nginx-ingress
  version: 3.30.0
  valuesContent: |-
    controller:
      admissionWebhooks:
        # Skip admission webhook for now because we don't wait for it to be ready, which would
        # cause problems when ingresses try to be created
        enabled: false
      service:
        # This forces velero to persist our nodePort configuration as per: https://github.com/vmware-tanzu/velero/issues/989
        # See: https://github.com/vmware-tanzu/velero/blob/ad31e6eda7f0dfb8f6f84be2c1339d729cc8fb37/pkg/restore/service_action.go#L79
        # Yes, this is literally a pre-rendered JSON manifest hardcoded here. Thanks Velero.
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"name":"nginx-ingress-ingress-nginx-controller","namespace":"nginx-ingress"},"spec":{"ports":[{"name":"http","nodePort":32080,"port":80,"protocol":"TCP","targetPort":"http"},{"name":"https","nodePort":32443,"port":443,"protocol":"TCP","targetPort":"https"}]}}'
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
