apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: velero
  namespace: kube-system
spec:
  chart: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  targetNamespace: velero
  version: 2.14.12
  valuesContent: |-
    ##
    ## Configuration settings that directly affect the Velero deployment YAML.
    ##

    # Details of the container image to use in the Velero deployment & daemonset (if
    # enabling restic). Required.
    image:
      repository: velero/velero
      tag: v1.5.3
      pullPolicy: IfNotPresent    

    # Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Enable access to Minio
    dnsPolicy: Default

    ##
    ## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
    ## and additional server settings.
    ##
    configuration:
      # Cloud provider being used (e.g. aws, azure, gcp).
      provider: aws

      # Parameters for the `default` BackupStorageLocation. See
      # https://velero.io/docs/v1.5/api-types/backupstoragelocation/
      backupStorageLocation:
        # Bucket to store backups in. Required.
        bucket: velero
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: http://minio-developer-environment:9000

      # Parameters for the `default` VolumeSnapshotLocation. See
      # https://velero.io/docs/v1.5/api-types/volumesnapshotlocation/
      volumeSnapshotLocation:
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: http://minio-developer-environment:9000

    # Info about the secret to be used by the Velero deployment, which
    # should contain credentials for the cloud provider IAM account you've
    # set up for Velero.
    credentials:
      # Whether a secret should be used as the source of IAM account
      # credentials. Set to false if, for example, using kube2iam or
      # kiam to provide IAM credentials for the Velero pod.
      useSecret: true
      secretContents:
        cloud: |
          [default]
          aws_access_key_id = minioaccess
          aws_secret_access_key = miniosecret

    # Whether to deploy the restic daemonset.
    deployRestic: true

    restic:
      # Enable access to Minio
      dnsPolicy: Default
